# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Set environment
      run: |
        echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

    - name: Setup UPX
      run: |
        cd ..
        wget https://github.com/upx/upx/releases/download/v4.2.1/upx-4.2.1-amd64_linux.tar.xz
        tar xf upx-4.2.1-amd64_linux.tar.xz
        echo "upx=../upx-4.2.1-amd64_linux/upx" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Set up xgo
      run: |
        docker pull techknowlogick/xgo:latest
        go install src.techknowlogick.com/xgo@latest

    - name: Build
      run: |
        mkdir bin
        mkdir out
        make releases

    - name: Upload To Artifact
      uses: actions/upload-artifact@main
      with:
        name: MacArthurGo-${{ env.sha_short }}
        path: |
          out/*.tar.gz
          out/*.zip

    - name: Upload To Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body: New Release.
        files: |
          out/*.tar.gz
          out/*.zip
          config.json.default
