name: Build Dev

on:
  workflow_dispatch:
  push:
    branches:
      - "dev"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  COMMIT_ID: "${{ github.sha }}"
  NAME: MacArthurGo
  CGO_ENABLED: 0

jobs:
  Build:
    name: Build binary CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin, android ]
        goarch: [ "386", amd64, arm64 ]
        exclude:
          - goos: darwin
            goarch: "386"
          - goos: android
            goarch: "386"
          - goos: android
            goarch: amd64
    steps:
      - uses: actions/checkout@v4

      - name: Set Environment
        run: |
          mkdir -p bin
          echo "SHASHORT=$(git rev-parse --short "${{ env.COMMIT_ID }}")" >> "$GITHUB_ENV"
          echo "BUILDTIME=$(date +'%Y-%m-%dT%H:%M:%SZ' -u)" >> $GITHUB_ENV

      - name: Set LDFLAGS
        run: |
          echo "LDFLAGS=-w -s -X 'MacArthurGo/base.Version=${SHASHORT}' -X 'MacArthurGo/base.Branch=Beta/dev' -X 'MacArthurGo/base.BuildTime=${{ env.BUILDTIME }}'" >> $GITHUB_ENV

      - name: Setup UPX
        run: |
          cd ..
          wget https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-amd64_linux.tar.xz
          tar xf upx-4.2.2-amd64_linux.tar.xz
          echo "upx=../upx-4.2.2-amd64_linux/upx" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -ldflags="${LDFLAGS}" -o bin/${{ env.NAME }}-${{ matrix.goos }}-${{ matrix.goarch }} ./
          chmod +x bin/${{ env.NAME }}-*

      - name: Rename Windows
        if: ${{ matrix.goos == 'windows' }}
        run: |
          mv MacArthurGo-windows-${{ matrix.goarch }} MacArthurGo-windows-${{ matrix.goarch }}.exe
        working-directory: bin

      - name: UPX Compress
        if: ${{ matrix.goos != 'darwin' }}
        run: |
          if [ ${{ matrix.goos }} != "windows" ] && [ ${{ matrix.goarch }} != "arm64" ]; then ${{ env.upx }} --lzma --best bin/${{ env.NAME }}-*; fi

      - name: Upload To Artifact
        if: ${{  success() }}
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.SHASHORT }}
          path: |
            bin/*

  Upload-Prerelease:
    permissions: write-all
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@main
        with:
          path: bin/

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: bin

      - name: Delete current release assets
        uses: 8Mi-Tech/delete-release-assets-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: Prerelease-${{ github.ref_name }}
          deleteOnlyFromDrafts: false

      - name: Set Env
        run: |
          echo "UPLOADTIME=$(date +'%Y-%m-%dT%H:%M:%SZ' -u)" >> $GITHUB_ENV
        shell: bash

      - name: Tag Repo
        uses: richardsimko/update-tag@v1.1.6
        with:
          tag_name: Prerelease-${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          cat > release.txt << 'EOF'
          Release created at ${{ env.UPLOADTIME }}
          Commit: ${{ env.COMMIT_ID }}
          Synchronize ${{ github.ref_name }} branch code updates, keeping only the latest version
          EOF

      - run: |
          cat > version.json << 'EOF'
          {"version": "${{ env.COMMIT_ID }}", "upload_time": "${{ env.UPLOADTIME }}"}
          EOF
        working-directory: bin

      - name: Upload Prerelease
        uses: softprops/action-gh-release@v2
        if: ${{  success() }}
        with:
          tag_name: Prerelease-${{ github.ref_name }}
          files: |
            bin/*
            bin/*/*
          prerelease: true
          generate_release_notes: true
          body_path: release.txt