# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Setup UPX
      run: |
        cd ..
        wget https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-amd64_linux.tar.xz
        tar xf upx-4.2.2-amd64_linux.tar.xz
        echo "upx=../upx-4.2.2-amd64_linux/upx" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v5

    - name: Build
      run: |
        mkdir bin
        mkdir out
        make releases

    - name: Upload To Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body: New Release.
        files: |
          out/*.tar.gz
          out/*.zip
          config.json.default
